name: habitat
channels:
  - aihabitat
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=1_llvm
  - attrs=21.4.0=pyhd8ed1ab_0
  - bzip2=1.0.8=h7b6447c_0
  - c-ares=1.18.1=h7f8727e_0
  - ca-certificates=2024.7.2=h06a4308_0
  - certifi=2022.12.7=py37h06a4308_0
  - cmake=3.14.0=h52cb24c_0
  - colorama=0.4.4=pyh9f0ad1d_0
  - cycler=0.11.0=pyhd8ed1ab_0
  - expat=2.4.4=h295c915_0
  - ffmpeg=4.3.2=h37c90e5_3
  - freetype=2.10.4=h0708190_1
  - fribidi=1.0.10=h36c2ea0_0
  - giflib=5.2.1=h36c2ea0_2
  - gitdb=4.0.9=pyhd8ed1ab_0
  - gitpython=3.1.27=pyhd8ed1ab_0
  - gmp=6.2.1=h58526e2_0
  - gnutls=3.6.13=h85f3911_1
  - habitat-sim-challenge-2022=0.2.1=py3.7_headless_bullet_linux_f02ce8317b4bcbccf1ed92a6436f6aabc9aecec6
  - habitat-sim-mutex=1.0=headless_bullet
  - headless=2.0=0
  - icu=67.1=he1b5a44_0
  - imageio=2.16.1=pyhcf75d05_0
  - imageio-ffmpeg=0.4.5=pyhd8ed1ab_0
  - jbig=2.1=h7f98852_2003
  - jpeg=9e=h7f98852_0
  - kiwisolver=1.4.0=py37h7cecad7_0
  - krb5=1.19.2=hac12032_0
  - lame=3.100=h7f98852_1001
  - lcms2=2.12=hddcbb42_0
  - ld_impl_linux-64=2.35.1=h7274673_9
  - lerc=3.0=h9c3ff4c_0
  - libblas=3.9.0=13_linux64_openblas
  - libcblas=3.9.0=13_linux64_openblas
  - libcurl=7.80.0=h0b77cf5_0
  - libdeflate=1.10=h7f98852_0
  - libedit=3.1.20210910=h7f8727e_0
  - libev=4.33=h7f8727e_1
  - libffi=3.3=he6710b0_2
  - libgcc-ng=11.2.0=h1d223b6_14
  - libgfortran-ng=11.2.0=h69a702a_14
  - libgfortran5=11.2.0=h5c6108e_14
  - libimagequant=2.17.0=h7f98852_1
  - liblapack=3.9.0=13_linux64_openblas
  - libllvm11=11.1.0=hf817b99_3
  - libnghttp2=1.46.0=hce63b2e_0
  - libopenblas=0.3.18=pthreads_h8fe5266_0
  - libpng=1.6.37=h21135ba_2
  - libssh2=1.9.0=h1ba5d50_1
  - libstdcxx-ng=11.2.0=he4da1e4_14
  - libtiff=4.3.0=h542a066_3
  - libwebp=1.2.2=h3452ae3_0
  - libwebp-base=1.2.2=h7f98852_1
  - libxcb=1.13=h7f98852_1004
  - libzlib=1.2.11=h36c2ea0_1013
  - llvm-openmp=13.0.1=he0ac6c6_1
  - lz4-c=1.9.3=h9c3ff4c_1
  - matplotlib=3.2.2=1
  - matplotlib-base=3.2.2=py37h1d35a4c_1
  - ncurses=6.3=h7f8727e_2
  - nettle=3.6=he412f7d_0
  - openh264=2.1.1=h780b84a_0
  - openjpeg=2.4.0=hb52868f_1
  - openssl=1.1.1w=h7f8727e_0
  - pip=21.2.2=py37h06a4308_0
  - pthread-stubs=0.4=h36c2ea0_1001
  - pyparsing=3.0.7=pyhd8ed1ab_0
  - python=3.7.11=h12debd9_0
  - python-dateutil=2.8.2=pyhd8ed1ab_0
  - python_abi=3.7=2_cp37m
  - quaternion=2022.2.10.14.20.39=py37h5e8e339_0
  - readline=8.1.2=h7f8727e_1
  - rhash=1.4.1=h3c74f83_1
  - scipy=1.7.3=py37hf2a6cf1_0
  - seaborn=0.12.2=py37h06a4308_0
  - six=1.16.0=pyh6c4a22f_0
  - smmap=3.0.5=pyh44b312d_0
  - sqlite=3.37.2=hc218d9a_0
  - tk=8.6.11=h1ccaba5_0
  - tornado=6.2=py37h5eee18b_0
  - tqdm=4.63.0=pyhd8ed1ab_0
  - typing_extensions=4.3.0=py37h06a4308_0
  - x264=1!161.3030=h7f98852_1
  - xorg-fixesproto=5.0=h7f98852_1002
  - xorg-inputproto=2.3.2=h7f98852_1002
  - xorg-kbproto=1.0.7=h7f98852_1002
  - xorg-libx11=1.7.2=h7f98852_0
  - xorg-libxau=1.0.9=h7f98852_0
  - xorg-libxcursor=1.2.0=h7f98852_0
  - xorg-libxdmcp=1.1.3=h7f98852_0
  - xorg-libxext=1.3.4=h7f98852_1
  - xorg-libxfixes=5.0.3=h7f98852_1004
  - xorg-libxi=1.7.10=h7f98852_0
  - xorg-libxinerama=1.1.4=h9c3ff4c_1001
  - xorg-libxrandr=1.5.2=h7f98852_1
  - xorg-libxrender=0.9.10=h7f98852_1003
  - xorg-randrproto=1.5.0=h7f98852_1001
  - xorg-renderproto=0.11.1=h7f98852_1002
  - xorg-xextproto=7.3.0=h7f98852_1002
  - xorg-xproto=7.0.31=h7f98852_1007
  - xz=5.2.5=h7b6447c_0
  - zlib=1.2.11=h36c2ea0_1013
  - zstd=1.5.2=ha95c52a_0
  - pip:
    - absl-py==1.0.0
    - addict==2.4.0
    - appdirs==1.4.4
    - astor==0.8.1
    - astunparse==1.6.3
    - backcall==0.2.0
    - backports-cached-property==1.0.2
    - beautifulsoup4==4.12.3
    - boto3==1.33.13
    - botocore==1.33.13
    - braceexpand==0.1.7
    - cachetools==5.0.0
    - charset-normalizer==2.0.12
    - click==8.0.4
    - clip==1.0
    - cloudpickle==2.0.0
    - comm==0.1.4
    - configargparse==1.7
    - dash==2.15.0
    - dash-core-components==2.0.0
    - dash-html-components==2.0.0
    - dash-table==5.0.0
    - decorator==4.4.2
    - distlib==0.3.8
    - docker-pycreds==0.4.0
    - docstring-parser==0.14.1
    - dtw==1.4.0
    - fastdtw==0.3.4
    - fastjsonschema==2.20.0
    - filelock==3.12.2
    - flask==2.2.5
    - flatbuffers==24.3.25
    - frozendict==2.4.4
    - ftfy==6.1.1
    - gast==0.4.0
    - gdown==4.7.3
    - google-auth==2.6.0
    - google-auth-oauthlib==0.4.6
    - google-pasta==0.2.0
    - grpcio==1.45.0rc1
    - gym==0.23.1
    - gym-notices==0.0.6
    - h5py==3.8.0
    - habitat-sim==0.2.1
    - huggingface-hub==0.0.12
    - idna==3.3
    - ifcfg==0.22
    - imagehash==4.3.1
    - imghash==0.1.0
    - importlib-metadata==6.7.0
    - importlib-resources==5.12.0
    - ipython==7.34.0
    - ipywidgets==8.1.3
    - itsdangerous==2.1.2
    - jedi==0.19.1
    - jinja2==3.1.4
    - jmespath==1.0.1
    - joblib==1.3.2
    - jsonlines==3.1.0
    - jsonschema==4.17.3
    - jupyter-core==4.12.0
    - jupyterlab-widgets==3.0.11
    - keras==2.11.0
    - keras-applications==1.0.8
    - keras-preprocessing==1.1.2
    - libclang==18.1.1
    - llvmlite==0.31.0
    - lmdb==1.3.0
    - markdown==3.3.6
    - markdown-it-py==2.2.0
    - markupsafe==2.1.5
    - matplotlib-inline==0.1.6
    - mdurl==0.1.2
    - mock==5.1.0
    - moviepy==2.0.0.dev2
    - msgpack==1.0.3
    - msgpack-numpy==0.4.7.1
    - nbformat==5.7.0
    - nest-asyncio==1.6.0
    - networkx==2.6.3
    - numba==0.48.0
    - numpy==1.21.6
    - oauthlib==3.2.0
    - objectio==0.2.29
    - open3d==0.17.0
    - opencv-python==4.5.5.64
    - opt-einsum==3.3.0
    - packaging==24.0
    - pandas==1.3.0
    - pandocfilters==1.5.0
    - parso==0.8.4
    - pathtools==0.1.2
    - pexpect==4.9.0
    - pickle5==0.0.12
    - pickleshare==0.7.5
    - pillow==7.2.0
    - pkgutil-resolve-name==1.3.10
    - platformdirs==3.11.0
    - plotly==5.18.0
    - prompt-toolkit==3.0.47
    - protobuf==3.19.6
    - psutil==6.0.0
    - ptyprocess==0.7.0
    - pyasn1==0.4.8
    - pyasn1-modules==0.2.8
    - pygments==2.17.2
    - pyliblzfse==0.4.1
    - pyquaternion==0.9.9
    - pyrsistent==0.19.3
    - pysocks==1.7.1
    - pytorch-transformers==1.2.0
    - pytz==2024.1
    - pywavelets==1.3.0
    - pyyaml==6.0
    - regex==2024.4.16
    - requests==2.27.1
    - requests-oauthlib==1.3.1
    - retrying==1.3.4
    - rich==13.7.1
    - rsa==4.8
    - s3transfer==0.8.2
    - sacremoses==0.0.53
    - scikit-image==0.19.3
    - scikit-learn==1.0.2
    - sentencepiece==0.2.0
    - sentry-sdk==2.7.1
    - setproctitle==1.3.3
    - setuptools==68.0.0
    - shtab==1.7.1
    - simplejson==3.17.6
    - soupsieve==2.4.1
    - tenacity==8.2.3
    - tensorboard==2.11.2
    - tensorboard-data-server==0.6.1
    - tensorboard-plugin-wit==1.8.1
    - tensorflow==2.11.0
    - tensorflow-estimator==2.11.0
    - tensorflow-io-gcs-filesystem==0.34.0
    - termcolor==2.3.0
    - threadpoolctl==3.1.0
    - tifffile==2021.11.2
    - tinycudann==1.7
    - tokenizers==0.10.3
    - torch==1.12.1+cu113
    - torch-kdtree==1.0
    - torchvision==0.13.1+cu113
    - traitlets==5.8.0
    - transformers==4.9.2
    - trimesh==3.9.1
    - trove-classifiers==2023.7.6
    - typeguard==3.0.2
    - typer==0.4.0
    - typing-extensions==4.7.1
    - tyro==0.5.2
    - urllib3==1.26.15
    - virtualenv==20.23.1
    - viser==0.0.10
    - wandb==0.15.2
    - wcwidth==0.2.5
    - webdataset==0.1.40
    - webencodings==0.5.1
    - websocket-client==1.4.2
    - websockets==11.0.3
    - werkzeug==2.2.3
    - wheel==0.37.1
    - widgetsnbextension==4.0.11
    - wrapt==1.14.1
    - xatlas==0.0.7
    - xxhash==3.2.0
    - yacs==0.1.8
    - zipp==3.7.0
prefix: /opt/conda/envs/habitat
